"""
Project Euler Problem 45
========================

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T[n]=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal   P[n]=n(3n-1)/2  1, 5, 12, 22, 35, ...
Hexagonal    H[n]=n(2n-1)    1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from math import sqrt


def solve_T(y):
    'Return the bigger solution'
    return (sqrt(1+8*y)-1) / 2


def solve_P(y):
    'Return the bigger solution'
    return (sqrt(1+24*y)+1) / 6


def main():
    for i in xrange(144, 10**5):
        y = i * (2*i-1)
        t, p = solve_T(y), solve_P(y)
        if t == int(t) and p == int(p):
            return y


if __name__ == '__main__':
    print main()
